# Generated by Django 2.1.4 on 2019-07-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titanic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titanic',
            name='Pclass',
            field=models.IntegerField(default=0),
        ),
    ]
